### ISSUE TITLE
Pixel_offset application

### ISSUE THREAD

**Issue by austingulliver** [austingulliver/chiron_slicer#12]
Is pixel_offset implemented  or not in the pipeline or not?

**Comment by Edison1999** [comment]
pixel_offset is used in mkwave2.pro

**Comment by Edison1999** [comment]
Picture for ThAr files in night 220210
![Image](https://github.com/austingulliver/chiron_slicer/assets/66285897/c53ce2b0-47eb-4d14-86dd-0545e1b698e4)

**2017 ThAr (black )**
reference pixels: 2149.1672,  2255.6048,  2577.3819,  3178.8910,  3358.9710

**220210 - 1003 ThAr (red)**
reference pixels: 2149.2340,  2255.5793,  2577.4489,  3179.0021,  3359.0232
pixel offset:    -0.054376870

**220210  - 1138 ThAr (green)**
reference pixels:  2149.2906,  2255.5849,   2577.5133,  3178.9528, 3359.0638
pixel offset:    -0.077939440

**220210  - 1146ThAr (blue)**
reference pixels: 2149.2846,  2255.6014, 2577.4434, 3178.9304, 3359.0691
pixel offset is  :    -0.062647686

**220210  - 1172 ThAr(pink )**
reference pixels: 2149.2556,  2255.5304, 2577.4899, 3178.9467,  3359.0449
pixel offset is  :    -0.050344385
