### ISSUE TITLE
Remove hardcoded paths in program

### ISSUE THREAD

**Issue by Edison1999** [austingulliver/chiron_slicer#13]
All paths should be read from the config file

**Comment by austingulliver** [comment]
Well done

Dr. Austin F. Gulliver
Professor and Chair
Department of Physics & Astronomy
Brandon University
Brandon, Manitoba R7A 6A9
204-727-7441
***@***.******@***.***>

From: Edison Lozano ***@***.***>
Sent: Saturday, September 30, 2023 11:58 PM
To: austingulliver/chiron_slicer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [austingulliver/chiron_slicer] Remove hardcoded paths in program (Issue #13)


All paths should be read from the config file
