### ISSUE TITLE
Introduce new variable in ctio

### ISSUE THREAD

**Issue by austingulliver** [austingulliver/chiron_slicer#20]
Add pixel_total to ctio.par. Needs to indicate the number of pixels used for each order. 

Remove hard-coded 3200 -> use for combine stellar?

Initial reduction starts with 4112 pixels but seems to use only 3200 when combine_stellar is use.

**Comment by Edison1999** [comment]
cut_spectra in reduce_slicer -> line 339 splice_type variable

**Comment by Edison1999** [comment]
pixel_to_cut variable has been added to ctio.par file.  To make it compatible need to add argument pixel_to_cut in ctio.par before running the pipeline.



![Image](https://github.com/austingulliver/chiron_slicer/assets/66285897/c5b6c5be-ebdd-4169-9f16-1415de3b72ee)
