### ISSUE TITLE
ThAr file selection for combine_stellar

### ISSUE THREAD

**Issue by Edison1999** [austingulliver/chiron_slicer#26]

**Comment by austingulliver** [comment]
Hi Edison,

Is the pipeline able to produce the coadded spectrum wmchi…. From a single command now? If so what is the command?

I just tried the usual /post_process command followed by the usual /post_process,/combine_stellar. Although the program ran, it did not create any wmchi…
File.

Regards,

Dr. Austin F. Gulliver
Professor and Chair
Department of Physics & Astronomy
Brandon University
Brandon, Manitoba R7A 6A9
204-727-7441
***@***.******@***.***>

From: Edison Lozano ***@***.***>
Sent: Tuesday, November 14, 2023 6:18 PM
To: austingulliver/chiron_slicer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [austingulliver/chiron_slicer] ThAr file selection for combine_stellar (Issue #26)

**Comment by Edison1999** [comment]
Hi Dr. Gulliver,

It should be the same command as before (/combine_stellar). Which files get created when you run it ?

Thanks,
Edison

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by austingulliver** [comment]
It should be creating the 3200 pixel version (I have set it to this to compare with previous results) of the wmchi… coadded FITS file in the 220122_processed subdirectory.

It did create the 4112 pixel files in the 220122 parent directory and the individual 3200 pixel files when I used the post_process command first.

I realize that I did not have to first use the post_process command; that may have caused a problem.

Regards,

Dr. Austin F. Gulliver
Professor and Chair
Department of Physics & Astronomy
Brandon University
Brandon, Manitoba R7A 6A9
204-727-7441
***@***.******@***.***>

**Comment by Edison1999** [comment]
No problem. I also run it locally in my machine and I was able to obtain the master files. If you are running the pipeline for 220122, you should get two wmchi.. files one for HR2618 call wmchi220210.1126_12.fits and the second one for HR3452 call wmchi220210.1142_4.fits.

Thanks,
Edison
________________________________
